config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,  :controllers => { registrations: "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :riders

  resources :riders do
    resources :albums, only: [:new, :create]
  end

   resources :riders do
    resources :events, only: [:new, :create]
  end

  resources :riders do
    resources :posts, only: [:new, :create]
  end

  resources :posts do
    resources :comments, only:[:new, :create, :destroy]
  end
  resources :posts do
    member {post :like}
  end


  resources :posts, only: [:index, :show, :edit, :update, :destroy]


  resources :albums, only: [:index, :show,:new, :edit, :update, :destroy]

  resources :events, only: [:index, :show, :edit, :update, :destroy]

  get '/pages/videos', to: 'pages#videos'
  get '/pages/events', to: 'pages#events'
  get '/pages/about', to: 'pages#about'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :rider
  has_attachments :photos, maximum: 15

  # def owns_album?(album)
  #   self.albums.include?(album) ? true : false
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :rider
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :rider
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :rider
  belongs_to :event
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :rider
  has_many :comments
  mount_uploader :foto, PhotoUploader
  # acts_as_votable
  has_reputation :likes, source: :user, aggregated_by: :sum

end

app/models/rider.rb
class Rider < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  validates :user_name, :first_name, :last_name, :age, :country, presence: true, on: :update
  has_many :albums
  has_many :posts, dependent: :destroy
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :rider
  # acts_as_voter

   def has_rider?
    self.rider != nil
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :set_rider, only: [:new, :create]

  def index
    @albums = policy_scope(Album)
  end

  def show
    @album = Album.find(params[:id])
    authorize @album
  end

  def new
    if @rider.user.admin
      @album = Album.new
      authorize @album
    else
      redirect_to root_path
    end
  end

  def create
    if @rider.user.admin
      @album = Album.create(album_params)
      @album.rider = current_user.rider
      authorize @album

      if @album.save
        redirect_to rider_path(@rider)
      else
        render :new
      end
    end
  end

  def edit
    @album = Album.find(params[:id])
    authorize @album
  end

  def update
    @album = Album.find(params[:id])
    @album.update(album_params)
    redirect_to album_path(@album)
    authorize @album
  end

  def destroy
    @album = Album.find(params[:id]).destroy
    redirect_to root_path
    authorize @album
  end

  private

  def album_params
    params.require(:album).permit(:title, :photographer, :location, photos:[])
  end

  def set_rider
    @rider = Rider.find(params[:rider_id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_rider, only: [:new, :create]
  def index
    @events = policy_scope(Event)
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
    if @rider.user.admin
      @event = Event.new
      authorize @event
    else
      redirect_to root_path
    end
  end

  def create
    if @rider.user.admin
      @event = Event.create(event_params)
      @event.rider = current_user.rider
      authorize @event

      if @event.save
        redirect_to rider_path(@rider)
      else
        render :new
      end
    end
  end

  def destroy
  end

  private

    def set_rider
    @rider = Rider.find(params[:rider_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @album = Album.last
    @post = Post.last
    @posts = Post.all
  end

  def videos

  end

  def events

  end

  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_rider, only: [:new, :create, :vote]
   before_action :set_post, only: [ :like]
   # respond_to :js, :json, :html
  def index
    @posts = policy_scope(Post)
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @comments = Comment.where(post_id: @post).order("created_at DESC")
  end

  def new
    @rider = Rider.find(params[:rider_id])
    @post = Post.new
    authorize @post

  end

  def create
    @post= Post.new(post_params)
    authorize @post
    @post.rider = current_user.rider
    @post.save
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
    authorize @post
  end

  def like
    value = params[:type] == "up" ? 1 : -1
     @post = Post.find(params[:id])
     authorize @post
     @post.add_or_update_evaluation(:likes, value, current_user)
     redirect_to :back
  end

  # def vote
  #   if !current_user.liked? @post
  #     @post.liked_by current_user.rider
  #   elsif current_user.liked? @post
  #     @post.unlike_by current_user
  #   end
  # end

  private

  def post_params
    params.require(:post).permit(:fotografo, :foto)
  end

  def set_rider
    @rider = Rider.find(params[:rider_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PTY Brothers</title>
    <meta name="description" content="Ptybrothers comunidad Unida por la Adrenalina! Movimiento que fue creado con el principal motivo de mantener la escena de los deportes extremos viva en Panamá. Nuestro objetivo es brindar apoyo a riders mediante material audiovisual de alta calidad que demuestre su talento, poniendo así a Panamá en el mapa de los deportes extremos. Se parte del movimiento!">
    <meta property="og:title" content="PTYB rothers">
    <meta property="og:description" content="Ptybrothers comunidad Unida por la Adrenalina! Movimiento que fue creado con el principal motivo de mantener la escena de los deportes extremos viva en Panamá. Nuestro objetivo es brindar apoyo a riders mediante material audiovisual de alta calidad que demuestre su talento, poniendo así a Panamá en el mapa de los deportes extremos. Se parte del movimiento!">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= render 'application/favicon' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Audiowide|Indie+Flower" rel="stylesheet">
  <style>
 .navbar-wagon-brand2 img {
  width: 70px;
}
.position{
   background: #070707;
  padding: 30px 0;
  color: #CCCCCC;
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    text-align: center;
}
.footerv2 {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #070707;
   color: white;
   text-align: center;
}
.responsive {
    width: 100%;
    height: auto;
}
.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
}
  </style>

</head>
<body class="Site">
  <%= render 'shared/navbarv2' %>
  <%= render 'shared/flashes' %>
    <%= yield %>
  <%= render 'shared/footerV2' %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
  <script src="lib/jquery-2.0.3.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<div class="about padded">
  <br>
  <br>
  <br>
  <br>
 <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 text-center">
      <%= image_tag("logo1.png")%>
    </div>
    <div class="col-xs-12 col-sm-6">
     <ul class="list-unstyled">
      <h2>PTY Brothers</h2>
      <li><p><strong>Founder</strong> Francisco J. Dutary</p></li>
      <li><p> <strong># Phone</strong> 6666-1442</p></li>
      <p><strong> Ptybrothers </strong>es un movimiento que fue creado con el principal motivo de mantener la escena de los deportes extremos viva en Panamá. Nuestro objetivo es brindar apoyo a riders mediante material audiovisual de alta calidad que demuestre su talento, poniendo así a Panamá en el mapa de los deportes extremos.</p>
      <li><p><strong>Contactanos</strong> ptybrothers@gmail.com </p> </li>
    </ul>
  </div>
</div>
</div>
<br>
<br>
</div>

app/views/pages/events.html.erb
<div class="text-center" style="padding-bottom: 40px;">
  <h2>Eventos</h2>
</div>
<div class="events text-center"">
<h2>Prontó</h2>
</div>
<br>

app/views/pages/home.html.erb
<!-- <div class="container">
<div class="row">
  <div class="col-xs-12 text-center meanwhile">
  <%= image_tag "logo1.png",  height: 300%>
  <h5>PTY Brothers v2.0.0 Soon</h5>
  </div>
</div>
</div> -->
<br>
<br>
<% if current_user %>
<br>
<br>
<br>
<br>
<% if @posts %>
<% @posts.reverse.each do |post|%>
<div class="container" style="padding-bottom: 50px">
  <div class="row">
    <div class="col-md-12 text-center">
      <%= link_to post_path(post) do %>
      <div class="text-center">
        <%= cl_image_tag post.foto, height: 500, crop: :fill, class: "img-responsive center", style: "border: 3px solid #000000;"%>
      </div>
      <%end%>
      <h2>Rider</h2>
      <h3>
        <%= link_to rider_path(post.rider) do %>
        <%= cl_image_tag post.rider.photo, height: 80, class: "avatar-small", style: "border-radius: 50%; border: 3px solid #000000;"%>
        <%= post.rider.first_name %> <%= post.rider.last_name %>
        <%end%>
      </h3>
      <h3><i class="fa fa-camera"></i> <%= post.fotografo %></h3>
      <h3><i class="fa fa-star"></i> <%= post.reputation_for(:likes).to_i%></h3>

      <p> <i class="fa fa-arrow-up"></i> <%= link_to "up", like_post_path(post,type:"up"), method: "post"%> </p>
       <p> <i class="fa fa-arrow-down"></i>  <%= link_to "down", like_post_path(post,type:"down"), method: "post"%> </p>
       <hr>
    </div>
  </div>
</div>
<% end %>
<%else%>
<h1>Fuck wait</h1>
<% end %>

<%else%>
<br>
   <div class="banner" style="background-image: url('<%= image_path('banner3.png')%> ');  background-position: center;">
    <div class="banner-content">
      <h1 style="color: white !important">PTY Brothers</h1>
      <h3 style="color: white !important">Comunidad Unida por la Adrenalina</h3>
      <p>Se parte del movimiento!</p>
      <%= link_to "Sing up", new_user_registration_path, class: "btn btn-bro"%>
    </div>
  </div>
<% end %>

app/views/pages/videos.html.erb
<div class="text-center" style="padding-bottom: 40px;">
  <h2>Videos</h2>
</div>
<div class="container">
  <div class="row">
    <div class ="text-center">
      <div class="col-xs-12">
        <h2>Fernando Garzia</h2>
        <h3>Location: CC3, Skate Park</h3>
        <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=CFlO_LyYUhQ">Fernando Garzia at CC3</a></h4><p>Film / edit Francisco J. Dutary</p></blockquote>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class ="text-center">
      <div class="col-xs-12">
        <h2>Jobo House Downhill Fest 2017</h2>
        <h3>Location: El jobo, La Chorrera</h3>
        <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=49g-Za0dydE">Jobo House Downhill Fest 2017</a></h4><p>Uploaded by PTY Brothers on 2017-06-28.</p></blockquote>
        <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class ="text-center">
      <div class="col-xs-12">
        <h2>Speed Trike Panama - GaboSpeedTrike</h2>
        <h3>Location: La Mayor, La Chorrera</h3>
        <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=L6l35tY2IQE">Speed Trike Panama - GaboSpeedTrike -LA MAYOR</a></h4><p>PRACTICAS PRE-LA LUCHA2018 "SPEED DEMONS TRIKES"</p></blockquote>
        <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class ="text-center">
      <div class="col-xs-12">
        <h2>Bullshit</h2>
        <h3>Cuti Valdez</h3>
        <h4>Location: Yeguada</h4>
        <blockquote class="embedly-card"><h4><a href="https://youtu.be/y-1CjBuQBJc">Bullshit - Cuti Valdes</a></h4><p>spot: La Yeguada song: Bullshit -Dune Rats</p></blockquote>
        <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class ="text-center">
      <div class="col-xs-12">
        <h2>Skatepark Sesh</h2>
        <h3>Santiago</h3>
        <h4>Location: CC3 Skate park</h4>
        <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=VdnENVNQEzc">Best of Santiago at Skatepark CC3</a></h4><p>Uploaded by PTY Brothers on 2017-04-03.</p></blockquote>
        <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
      </div>
    </div>
  </div>
</div>
<br>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href="https://www.youtube.com/user/1331panchito"><i class="fa fa-youtube"></i></a></li>
          <li><a href="https://www.instagram.com/ptybrothers/"><i class="fa fa-instagram"></i></a></li>
          <li><a href="https://www.facebook.com/PTYBrothers/?hc_ref=SEARCH"><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
       <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.png" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footerV2.html.erb
  <div class="footerv2">
    <div class="row">
      <div class="text-center">
       <a href="http://www.leonardoluxburg.com" class="navbar-wagon-brand2">
        <br>
        <%= image_tag "logollwhite.png" %>
        <br>
        <br>
      </a>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed" >
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo1.png" %>
  <% end %>

  <!-- Right Navigation -->
 <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
           <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
           <li>
            <%= link_to posts_path do %>
            <i class="fa fa-globe"></i>  <%= t(".profile", default: "Mundo") %>
            <% end %>
          </li>
           <li>
            <%= link_to albums_path do %>
            <i class="fa fa-image"></i>  <%= t(".profile", default: "Media") %>
            <% end %>
          </li>
          <li>
            <%= link_to rider_path(current_user.rider) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <%end%>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>

    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn btn-bro" %>
    <%= link_to t(".sign_in", default: "Sing Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
        <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
           <li>
            <%= link_to "#" do %>
            <i class="fa fa-globe"></i>  <%= t(".profile", default: "Mundo") %>
            <% end %>
          </li>
           <li>
            <%= link_to "#" do %>
            <i class="fa fa-image"></i>  <%= t(".profile", default: "Media") %>
            <% end %>
          </li>
          <li>
            <%= link_to rider_path(current_user.rider) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <%end%>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
           <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/shared/_navbarv2.html.erb
<div class="navbar-wagon navbar-wagon-fixed" >
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo1.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
       <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
           <li>
            <%= link_to root_path do %>
            <i class="fa fa-globe"></i>  <%= t(".profile", default: "Mundo") %>
            <% end %>
          </li>
            <li>
            <%= link_to rider_path(current_user.rider) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <%end%>
          </li>
           <li>
            <%= link_to albums_path do %>
            <i class="fa fa-image"></i>  <%= t(".profile", default: "Media") %>
            <% end %>
          </li>
          <li>
            <a href="https://www.youtube.com/user/1331panchito">
              <i class="fa fa-youtube"></i> Videos
            </a>
          </li>
            <li>
            <a href="https://www.instagram.com/ptybrothers/">
              <i class="fa fa-instagram"></i> Instragram
            </a>
          </li>
            <li>
            <%= link_to pages_about_path do %>
            <i class="fa fa-thumbs-up"></i>  Contact us
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
     </div>
   </div>
   <% else %>

   <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item  btn btn-bro" %>
   <% end %>

 </div>
</div>