config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,  :controllers => { registrations: "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :riders

  resources :riders do
    resources :albums, only: [:new, :create]
  end

   resources :riders do
    resources :events, only: [:new, :create]
  end

  resources :riders do
    resources :posts, only: [:new, :create]
  end

  resources :posts do
    resources :comments, only:[:new, :create, :destroy]
  end
  resources :posts do
    member {post :like}
  end


  resources :posts, only: [:index, :show, :edit, :update, :destroy]


  resources :albums, only: [:index, :show,:new, :edit, :update, :destroy]

  resources :events, only: [:index, :show, :edit, :update, :destroy]

  get '/pages/videos', to: 'pages#videos'
  get '/pages/events', to: 'pages#events'
  get '/pages/about', to: 'pages#about'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :rider
  has_attachments :photos, maximum: 15

  # def owns_album?(album)
  #   self.albums.include?(album) ? true : false
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :rider
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :rider
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :rider
  belongs_to :event
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :rider
  has_many :comments
  mount_uploader :foto, PhotoUploader
  # acts_as_votable
  has_reputation :likes, source: :user, aggregated_by: :sum

end

app/models/rider.rb
class Rider < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  validates :user_name, :first_name, :last_name, :age, :country, presence: true, on: :update
  has_many :albums
  has_many :posts, dependent: :destroy
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :rider
  # acts_as_voter

   def has_rider?
    self.rider != nil
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :set_rider, only: [:new, :create]

  def index
    @albums = policy_scope(Album)
  end

  def show
    @album = Album.find(params[:id])
    authorize @album
  end

  def new
    if @rider.user.admin
      @album = Album.new
      authorize @album
    else
      redirect_to root_path
    end
  end

  def create
    if @rider.user.admin
      @album = Album.create(album_params)
      @album.rider = current_user.rider
      authorize @album

      if @album.save
        redirect_to rider_path(@rider)
      else
        render :new
      end
    end
  end

  def edit
    @album = Album.find(params[:id])
    authorize @album
  end

  def update
    @album = Album.find(params[:id])
    @album.update(album_params)
    redirect_to album_path(@album)
    authorize @album
  end

  def destroy
    @album = Album.find(params[:id]).destroy
    redirect_to root_path
    authorize @album
  end

  private

  def album_params
    params.require(:album).permit(:title, :photographer, :location, photos:[])
  end

  def set_rider
    @rider = Rider.find(params[:rider_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy]
  def create
    @comment = @post.comments.create(comment_params)
    @comment.rider = current_user.rider
    @comment.save
    authorize @comment
    redirect_to post_path(@post)

  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post=Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_rider, only: [:new, :create]
  def index
    @events = policy_scope(Event)
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
    if @rider.user.admin
      @event = Event.new
      authorize @event
    else
      redirect_to root_path
    end
  end

  def create
    if @rider.user.admin
      @event = Event.create(event_params)
      @event.rider = current_user.rider
      authorize @event

      if @event.save
        redirect_to rider_path(@rider)
      else
        render :new
      end
    end
  end

  def destroy
  end

  private

    def set_rider
    @rider = Rider.find(params[:rider_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @album = Album.last
    @post = Post.last
    @posts = Post.all
  end

  def videos

  end

  def events

  end

  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_rider, only: [:new, :create, :vote]
   before_action :set_post, only: [ :like]
   # respond_to :js, :json, :html
  def index
    @posts = policy_scope(Post)
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @comments = Comment.where(post_id: @post).order("created_at DESC")
  end

  def new
    @rider = Rider.find(params[:rider_id])
    @post = Post.new
    authorize @post

  end

  def create
    @post= Post.new(post_params)
    authorize @post
    @post.rider = current_user.rider
    @post.save
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
    authorize @post
  end

  def like
    value = params[:type] == "up" ? 1 : -1
     @post = Post.find(params[:id])
     authorize @post
     @post.add_or_update_evaluation(:likes, value, current_user)
     redirect_to :back
  end

  # def vote
  #   if !current_user.liked? @post
  #     @post.liked_by current_user.rider
  #   elsif current_user.liked? @post
  #     @post.unlike_by current_user
  #   end
  # end

  private

  def post_params
    params.require(:post).permit(:fotografo, :foto)
  end

  def set_rider
    @rider = Rider.find(params[:rider_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController

  def index
    @riders = policy_scope(Rider)
    @riders
  end

  def show
    @user = current_user
    @rider = Rider.find(params[:id])
    authorize @rider
  end

  def edit
    @rider = Rider.find(params[:id])
    authorize @rider
  end

  def update
    @rider = Rider.find(params[:id])
    @rider.update(rider_params)
    redirect_to rider_path(@rider)
    authorize @rider
  end


  private

  def rider_params
    params.require(:rider).permit(:user_name, :first_name, :last_name, :age, :description, :country, :photo, :photo_cache)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/views/albums/edit.html.erb
  <h1 class="text-center"><%= @album.title%></h1>
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
        <%= simple_form_for @album do |f| %>
        <%= f.input :title %>
        <%= f.input :photographer %>
        <%= f.input :location %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="text-center padded">
  <%if current_user.rider.id == @album.rider_id%>
  <%= link_to "Delete",album_path(@album), method: :delete, class: 'btn btn-danger'%>
  <%end%>
</div>

app/views/albums/index.html.erb
<% @albums.each do |album| %>
<div class="banner" style="background-image:url('<%= cl_image_path album.photos.first.path %>'); background-position: center; ">
  <%= link_to album_path(album) do %>
  <div class="banner-content">
    <h1><%=album.title%></h1>
    <h4><i class="fa fa-camera"></i> <%=album.photographer%></h4>
    <h4><i class="fa fa-location"></i> <%=album.location%></h4>
  </div>
  <% end %>
</div>
<% end %>

app/views/albums/new.html.erb
<div class= "text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
        <%= simple_form_for [@rider, @album] do |f| %>
        <%= f.input :title %>
        <%= f.input :photographer %>
        <%= f.input :location %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.submit class: "btn btn-bro" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row text-center">
  <h2><%= @album.title %></h2>
    <h3><%= @album.location %></h3>
      <h4><%= @album.photographer %></h4>


  <hr>
     <%@album.photos.each_with_index  do |photo,index|%>
              <div class="text-center">
                <br>
              <%= cl_image_tag photo.path, height: 500, crop: :fill, class: "img-responsive center" %>
              <br>
              </div>
    <% end %>
    <hr>
    <hr>
    <%@album.photos.each_with_index  do |photo,index|%>
    <% modal = "#myModal" + index.to_s %>
    <% modalid = "myModal" + index.to_s %>
    <div class="col-xs-4">
      <a  class="btn btn-foto" data-toggle="modal" data-target=<%= modal %>>
        <%= cl_image_tag photo.path, height: 150, crop: :fill, class: "img-responsive pic-border" %>
      </a>
      <div id=<%= modalid %> class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= @album.title%></h4>
            </div>
            <div class="modal-body">
              <%= cl_image_tag photo.path, height: 500, crop: :fill, class: "img-responsive" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <hr>
  </div>
</div>
<div class = "text-center padded">
  <%if current_user.rider.id == @album.rider_id%>
  <%= link_to "Edit", edit_album_path(@album), class: 'btn btn-bro'%>
  <%end%>
</div>

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>

  <p><%= comment.content %></p>

<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<div class= "text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
      <%= simple_form_for [@post, @post.comments.build] do |f| %>
        <%= f.input :content %>
        <%= f.submit "Comment", class: "btn btn-bro" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/posts/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
        <br>
        <h2>Edit</h2>
      <%= simple_form_for [@rider, @post] do |f| %>
        <%= f.input :fotografo %>
        <%= f.input :foto %>
        <%= f.input :foto_cache, as: :hidden %>
        <%= f.submit "Add Post", class: "btn btn-danger" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<h2 class="text-center">World</h2>
<br>
<% @posts.reverse.each do |post|%>
<div class="container" style="padding-bottom: 150px">
  <div class="row">
    <div class="col-md-12 text-center">
    <%= link_to post_path(post) do %>
      <div class="text-center">
        <%= cl_image_tag post.foto,  height: 300, class: "responsive", style: "border: 3px solid #000000;"%>
      </div>
    <%end%>
      <h2>Rider</h2>
      <h3>
        <%= link_to rider_path(post.rider) do %>
        <%= cl_image_tag post.rider.photo, height: 80, class: "avatar-small", style: "border-radius: 50%; border: 3px solid #000000;"%>
        <%= post.rider.first_name %> <%= post.rider.last_name %>
        <%end%>
      </h3>
      <h3><i class="fa fa-camera"></i> <%= post.fotografo %></h3>
      <h3><i class="fa fa-star"></i> <%= post.reputation_for(:likes).to_i%></h3>
      <%= link_to "up", like_post_path(post,type:"up"), method: "post"%>
      <%= link_to "down", like_post_path(post,type:"down"), method: "post"%>
    </div>
  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
       <h2>Nuevo post</h2>
      <%= simple_form_for [@rider, @post] do |f| %>
        <%= f.input :fotografo %>
        <%= f.input :foto %>
        <%= f.input :foto_cache, as: :hidden %>
        <%= f.submit "Add Post", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>
<br>
<div class="container text-center">
   <p>*Contenido Indevido sera removido por los administradores y la cuenta sera eliminada*</p>
</div>

app/views/posts/show.html.erb
<br>
<br>
<br>
<h1 style="padding-top: 50px"></h1>
<div class="text-center">
  <div class="container">
  <%= cl_image_tag @post.foto,  height: 450, class: "img-responsive center-block", style: "border: 3px solid #000000;"%>
  </div>
</div>
<div class="container" style="padding-bottom: 50px">
  <div class="row">
   <div class="text-center">
    <h2>Rider</h2>
    <%= link_to rider_path(@post.rider) do %>
    <h3>
      <%= cl_image_tag @post.rider.photo, height: 80, class: "avatar-small", style: "border-radius: 50%; border: 3px solid #000000;"%>
      <%= @post.rider.first_name %> <%= @post.rider.last_name %>
    </h3>
    <% end %>
    <h3><i class="fa fa-camera"></i> <%= @post.fotografo %></h3>
    <h3><i class="fa fa-star"></i> <%= @post.reputation_for(:likes).to_i%></h3>
    <%= link_to "up", like_post_path(@post,type:"up"), method: "post"%>
    <%= link_to "down", like_post_path(@post,type:"down"), method: "post"%>
  </div>
</div>
</div>
<div>
  <div class="container">
    <div class="row">
      <div class="text-left">
        <h3>Comments</h3>
        <%= render 'comments/comment' %>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/posts/vote.js.erb
<% if current_user.rider.liked? @post %>
$('.like-btn').addClass('liked')
<%else %>
$('.like-btn').removeClass('liked')
<% end %>
$('.likes-count').html("<%= @post.get_upvotes.size% >")

app/views/riders/edit.html.erb
  <%# if current_user.owns_rider?(@profile) %>
  <br>
  <br>
  <br>
  <br>
  <h1 class="text-center">Rider</h1>
   <div class="container">
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
          <%= simple_form_for @rider do |f| %>
              <%= f.input :user_name %>
              <%= f.input :first_name %>
              <%= f.input :last_name %>
              <%= f.input :country %>
              <%= f.input :age %>
              <%= f.input :description %>
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
              <%= f.submit class: "btn btn-bro"%>
          <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/riders/index.html.erb
<h1 class="text-center">Riders</h1>
<div class="container">
  <div class="row">
    <% @riders.each do |rider|%>
    <% if rider.team_rider %>
    <%= link_to rider_path(rider) do %>
    <div class="col-xs-12 col-sm-6 text-center">
      <h3><%=rider.first_name + " " +rider.last_name%></h3>
        <%=image_tag rider.photo, class: "avatar-large"%>
    </div>
    <%end%>
    <%end%>
    <%end%>
  </div>
</div>
<br>
<br>

app/views/riders/show.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
     <h3><%=@rider.first_name %> <%=@rider.last_name %></h3>
     <%= cl_image_tag @rider.photo, height: 150 , crop: :fill, class: "" %>
     <h4><strong>User name: </strong><%=@rider.user_name%></h4>
     <h4><strong>Age: </strong><%=@rider.age%></h4>
     <h4><strong>Origin: </strong><%=@rider.country%></h4>
     <h4><%=@rider.description%></h4>
   </div>
 </div>
</div>
<br>
<div class="text-center">
 <%if current_user.rider.id == @rider.id%>
 <%= link_to "Edit", edit_rider_path(@rider), class: 'btn btn-bro'%>
 <%end%>
</div>

<div class="text-center" style="padding-bottom: 20px; padding-top: 20px;">
  <% if @user.admin %>
  <%if current_user.rider.id == @rider.id%>
  <%= link_to "Add Session", new_rider_album_path(@rider), class: "btn btn-danger"%>
  <%end%>
  <%end%>
</div>
<div class="container">
<div class="text-center" style="padding-bottom: 20px; padding-top: 20px;">
 <%if current_user.rider.id == @rider.id%>
 <h2>Add post</h2>
 <%= link_to new_rider_post_path(@rider) do %>
 <h2><i class="fa fa-plus"></i></h2>
 <%end%>
 <%end%>
</div>
</div>
<div class="container">
<div class="row">
  <hr>
  <% @rider.posts.reverse.each do |post|%>
  <div class="col-md-4">
  <%= link_to post_path(post) do %>
      <div class="text-center" style="padding-bottom:70px">
        <%= cl_image_tag post.foto,  height: 200, crop: :fill, class: "img-responsive", style: "border: 3px solid #000000;"%>
      </div>
    <% end %>
  </div>
  <% end %>
  <br>
</div>
</div>
<br>
<br>
<br>
<br>